baseURL = "https://hugomodo.github.io/"
languageCode = "en-us"
title = "HugoModo"

theme = [
  "hugomodo-cookie-consent",
  "hugomodo-fusejs",
  "hugomodo-shortcode-partials",
  "hugomodo-image-processing",
  "hugomodo-best-motherfucking-website"
]

pygmentsCodeFences = true
enableEmoji = true

googleAnalytics = "UA-58994131-3"
disqusShortname = "hugomodo"

[Params]
  description = "A modular Hugo framework."
  include_toc = true

[outputs]
  home = [
    "HTML",
    "RSS",
    "JSON"
  ]

[social]
  github = "hugomodo"

[Taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
