baseURL = "http://example.org/"
languageCode = "en-us"
title = "HugoModo"
theme = [
  "hugomodo-best-motherfucking-website"
]
pygmentsCodeFences = true
[Params]
  description = "A modular Hugo framework."
