baseURL = "https://hugomodo.github.io/"
languageCode = "en-us"
title = "HugoModo"

theme = [
  "hugomodo-shortcode-partials",
  "hugomodo-image-processing",
  "hugomodo-best-motherfucking-website"
]

pygmentsCodeFences = true

[Params]
  description = "A modular Hugo framework."
