---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/docs
  label: Docs
  create: all
  match: "**/*"
- type: directory
  path: content/extensions
  label: Extensions
  create: all
  match: "**/*"
- type: directory
  path: content/uploads
  label: Uploads
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/themes
  label: Themes
  create: all
  match: "**/*"
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.53'
